/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as StagesIndexRouteImport } from './routes/stages.index'
import { Route as StagesStageRouteImport } from './routes/stages.$stage'
import { Route as StagesStageIndexRouteImport } from './routes/stages.$stage.index'
import { Route as StagesStageGradeSubjectRouteImport } from './routes/stages.$stage.$grade.$subject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesIndexRoute = StagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StagesRoute,
} as any)
const StagesStageRoute = StagesStageRouteImport.update({
  id: '/$stage',
  path: '/$stage',
  getParentRoute: () => StagesRoute,
} as any)
const StagesStageIndexRoute = StagesStageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StagesStageRoute,
} as any)
const StagesStageGradeSubjectRoute = StagesStageGradeSubjectRouteImport.update({
  id: '/$grade/$subject',
  path: '/$grade/$subject',
  getParentRoute: () => StagesStageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/stages': typeof StagesRouteWithChildren
  '/stages/$stage': typeof StagesStageRouteWithChildren
  '/stages/': typeof StagesIndexRoute
  '/stages/$stage/': typeof StagesStageIndexRoute
  '/stages/$stage/$grade/$subject': typeof StagesStageGradeSubjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/stages': typeof StagesIndexRoute
  '/stages/$stage': typeof StagesStageIndexRoute
  '/stages/$stage/$grade/$subject': typeof StagesStageGradeSubjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/stages': typeof StagesRouteWithChildren
  '/stages/$stage': typeof StagesStageRouteWithChildren
  '/stages/': typeof StagesIndexRoute
  '/stages/$stage/': typeof StagesStageIndexRoute
  '/stages/$stage/$grade/$subject': typeof StagesStageGradeSubjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/services'
    | '/stages'
    | '/stages/$stage'
    | '/stages/'
    | '/stages/$stage/'
    | '/stages/$stage/$grade/$subject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/services'
    | '/stages'
    | '/stages/$stage'
    | '/stages/$stage/$grade/$subject'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/services'
    | '/stages'
    | '/stages/$stage'
    | '/stages/'
    | '/stages/$stage/'
    | '/stages/$stage/$grade/$subject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ServicesRoute: typeof ServicesRoute
  StagesRoute: typeof StagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/': {
      id: '/stages/'
      path: '/'
      fullPath: '/stages/'
      preLoaderRoute: typeof StagesIndexRouteImport
      parentRoute: typeof StagesRoute
    }
    '/stages/$stage': {
      id: '/stages/$stage'
      path: '/$stage'
      fullPath: '/stages/$stage'
      preLoaderRoute: typeof StagesStageRouteImport
      parentRoute: typeof StagesRoute
    }
    '/stages/$stage/': {
      id: '/stages/$stage/'
      path: '/'
      fullPath: '/stages/$stage/'
      preLoaderRoute: typeof StagesStageIndexRouteImport
      parentRoute: typeof StagesStageRoute
    }
    '/stages/$stage/$grade/$subject': {
      id: '/stages/$stage/$grade/$subject'
      path: '/$grade/$subject'
      fullPath: '/stages/$stage/$grade/$subject'
      preLoaderRoute: typeof StagesStageGradeSubjectRouteImport
      parentRoute: typeof StagesStageRoute
    }
  }
}

interface StagesStageRouteChildren {
  StagesStageIndexRoute: typeof StagesStageIndexRoute
  StagesStageGradeSubjectRoute: typeof StagesStageGradeSubjectRoute
}

const StagesStageRouteChildren: StagesStageRouteChildren = {
  StagesStageIndexRoute: StagesStageIndexRoute,
  StagesStageGradeSubjectRoute: StagesStageGradeSubjectRoute,
}

const StagesStageRouteWithChildren = StagesStageRoute._addFileChildren(
  StagesStageRouteChildren,
)

interface StagesRouteChildren {
  StagesStageRoute: typeof StagesStageRouteWithChildren
  StagesIndexRoute: typeof StagesIndexRoute
}

const StagesRouteChildren: StagesRouteChildren = {
  StagesStageRoute: StagesStageRouteWithChildren,
  StagesIndexRoute: StagesIndexRoute,
}

const StagesRouteWithChildren =
  StagesRoute._addFileChildren(StagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ServicesRoute: ServicesRoute,
  StagesRoute: StagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
